Repository kgateway-dev/pr-kind-labeler, pull requests merged in 2025-05, with the labels that each got.

#2 Prefix labels with kind/
  main.go
Labels: release-note-invalid, kind/breaking_change, release-note-needed

#3 Remove release-note-invalid label when valid release note is added
  main.go
Labels: release-note-needed, kind/bug_fix

#6 *: Add unit tests for the labeler package
  .github/workflows/unit.yaml
  go.mod
  go.sum
  internal/labeler/labeler_test.go
Labels: kind/cleanup, release-note-none

#7 internal/labeler: Validate a kind type has been supplied
  internal/labeler/labeler.go
  internal/labeler/labeler_test.go
Labels: release-note, kind/fix

#8 internal/labeler: Refactor error handling to avoid exiting early
  internal/labeler/labeler.go
  internal/labeler/labeler_test.go
Labels: release-note, kind/fix

#9 .github/workflows: Update unit workflow's push trigger
  .github/workflows/unit.yaml
Labels: kind/cleanup, release-note-none

#10 internal/labeler: Migrate deprecated labels to new types
  internal/labeler/labeler.go
  internal/labeler/labeler_test.go
Labels: release-note, kind/fix

#11 internal/labeler: Sync the do-not-merge/kind-invalid label correctly
  internal/labeler/labeler.go
  internal/labeler/labeler_test.go
Labels: release-note, kind/fix

#12 internal/labeler: Fix references to the release-notes-needed label
  internal/labeler/labeler.go
  internal/labeler/labeler_test.go
Labels: release-note, kind/fix

#13 make the errors more clear, and allow manual testing
  internal/labeler/labeler.go
  internal/labeler/labeler_test.go
  main.go
Labels: kind/cleanup, do-not-merge/release-note-invalid

#14 Move wellknown supported kinds and labels to pkg/
  internal/labeler/labeler.go
  internal/labeler/labeler_test.go
  pkg/kinds/kinds.go
  pkg/labels/labels.go
Labels: kind/cleanup, release-note-none

#15 Remove the .github/PULL_REQUEST_TEMPLATE.md template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/cleanup, release-note-none
